/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/wrangler.jsonc --include-runtime=false apps/worker/worker-configuration.d.ts` (hash: 068c915263ce71bb2a7d22b94e675e8a)
interface __BaseEnv_Env {
  ROUTING_CACHE?: KVNamespace;
  ORGANIZATION_FILES?: R2Bucket;
  CONTROL_DB?: D1Database;
  JOBS_QUEUE?: Queue;
  ASSETS: Fetcher;
  APP_ENV: "staging" | "production" | "local";
  BUILD_VERSION: "staging" | "unreleased" | "development";
  EXTERNAL_EFFECTS_MODE: "fake" | "disabled";
  PLATFORM_EMAIL_MODE: "capture" | "disabled";
  PRODUCT_BASE_DOMAIN:
    | "choir-management-cloudflare-staging.wes-osborn-account.workers.dev"
    | "invalid.example"
    | "localhost";
  ORGANIZATION_STORE?: DurableObjectNamespace<import("./src/index").OrganizationStore>;
  PROVISIONING_WORKFLOW?: Workflow<
    Parameters<import("./src/index").ProvisioningWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "OrganizationStore";
  }
  interface StagingEnv {
    ROUTING_CACHE: KVNamespace;
    ORGANIZATION_FILES: R2Bucket;
    CONTROL_DB: D1Database;
    JOBS_QUEUE: Queue;
    ASSETS: Fetcher;
    APP_ENV: "staging";
    BUILD_VERSION: "staging";
    EXTERNAL_EFFECTS_MODE: "fake";
    PLATFORM_EMAIL_MODE: "capture";
    PRODUCT_BASE_DOMAIN: "choir-management-cloudflare-staging.wes-osborn-account.workers.dev";
    ORGANIZATION_STORE: DurableObjectNamespace<import("./src/index").OrganizationStore>;
    PROVISIONING_WORKFLOW: Workflow<
      Parameters<import("./src/index").ProvisioningWorkflow["run"]>[0]["payload"]
    >;
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
    APP_ENV: "production";
    BUILD_VERSION: "unreleased";
    EXTERNAL_EFFECTS_MODE: "disabled";
    PLATFORM_EMAIL_MODE: "disabled";
    PRODUCT_BASE_DOMAIN: "invalid.example";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "APP_ENV"
      | "BUILD_VERSION"
      | "EXTERNAL_EFFECTS_MODE"
      | "PLATFORM_EMAIL_MODE"
      | "PRODUCT_BASE_DOMAIN"
    >
  > {}
}
