/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/wrangler.jsonc --include-runtime=false apps/worker/worker-configuration.d.ts` (hash: 0728213ee303667fc91f2308f9f65b97)
interface __BaseEnv_Env {
  ROUTING_CACHE?: KVNamespace;
  ORGANIZATION_FILES?: R2Bucket;
  CONTROL_DB?: D1Database;
  PLATFORM_EMAIL?: SendEmail;
  JOBS_QUEUE?: Queue;
  ASSETS: Fetcher;
  APP_ENV: "staging" | "production" | "local";
  BUILD_VERSION: "staging" | "unreleased" | "development";
  CUSTOM_DOMAIN_PROVIDER_MODE: "cloudflare" | "disabled" | "fake";
  EMAIL_EVENTS_DLQ_NAME:
    | "choir-management-email-events-dlq-staging"
    | "choir-management-email-events-dlq-production"
    | "choir-management-email-events-dlq-local";
  EMAIL_EVENTS_QUEUE_NAME:
    | "choir-management-email-events-staging"
    | "choir-management-email-events-production"
    | "choir-management-email-events-local";
  EXTERNAL_EFFECTS_MODE: "sandbox" | "disabled" | "fake";
  JOBS_DLQ_NAME:
    | "choir-management-jobs-dlq-staging"
    | "choir-management-jobs-dlq-production"
    | "choir-management-jobs-dlq-local";
  PLATFORM_EMAIL_ALLOWED_RECIPIENTS?: "dsksfjksjfakjsdf@dkfjsajfdskaj.test,cwosborn@gmail.com,qual-delivery-20260812-luna@qa-mail.staging.musicsite.org,qual-audition-20260812-luna@qa-mail.staging.musicsite.org,qual-unsubscribe-20260812-luna@qa-mail.staging.musicsite.org,qual-email-old-20260812-luna@qa-mail.staging.musicsite.org,qual-email-new-20260812-luna@qa-mail.staging.musicsite.org,qual-photo-member-20260812-luna@qa-mail.staging.musicsite.org,qual-identity-20260813-luna@qa-mail.staging.musicsite.org";
  PLATFORM_EMAIL_FROM: "auth@mail.staging.musicsite.org" | "auth@invalid.example";
  PLATFORM_EMAIL_MODE: "sandbox" | "disabled" | "capture";
  PRODUCT_BASE_DOMAIN: "staging.musicsite.org" | "invalid.example" | "localhost";
  STRIPE_PAYMENTS_ENABLED?: "true";
  ORGANIZATION_STORE?: DurableObjectNamespace<import("./src/index").OrganizationStore>;
  FLEET_SCHEMA_WORKFLOW?: Workflow<
    Parameters<import("./src/index").FleetSchemaWorkflow["run"]>[0]["payload"]
  >;
  PROVISIONING_WORKFLOW?: Workflow<
    Parameters<import("./src/index").ProvisioningWorkflow["run"]>[0]["payload"]
  >;
  CUSTOM_DOMAIN_WORKFLOW?: Workflow<
    Parameters<import("./src/index").CustomDomainWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "OrganizationStore";
  }
  interface StagingEnv {
    ROUTING_CACHE: KVNamespace;
    ORGANIZATION_FILES: R2Bucket;
    CONTROL_DB: D1Database;
    PLATFORM_EMAIL: SendEmail;
    JOBS_QUEUE: Queue;
    ASSETS: Fetcher;
    APP_ENV: "staging";
    BUILD_VERSION: "staging";
    CUSTOM_DOMAIN_PROVIDER_MODE: "cloudflare";
    EMAIL_EVENTS_DLQ_NAME: "choir-management-email-events-dlq-staging";
    EMAIL_EVENTS_QUEUE_NAME: "choir-management-email-events-staging";
    EXTERNAL_EFFECTS_MODE: "sandbox";
    JOBS_DLQ_NAME: "choir-management-jobs-dlq-staging";
    PLATFORM_EMAIL_ALLOWED_RECIPIENTS: "dsksfjksjfakjsdf@dkfjsajfdskaj.test,cwosborn@gmail.com,qual-delivery-20260812-luna@qa-mail.staging.musicsite.org,qual-audition-20260812-luna@qa-mail.staging.musicsite.org,qual-unsubscribe-20260812-luna@qa-mail.staging.musicsite.org,qual-email-old-20260812-luna@qa-mail.staging.musicsite.org,qual-email-new-20260812-luna@qa-mail.staging.musicsite.org,qual-photo-member-20260812-luna@qa-mail.staging.musicsite.org,qual-identity-20260813-luna@qa-mail.staging.musicsite.org";
    PLATFORM_EMAIL_FROM: "auth@mail.staging.musicsite.org";
    PLATFORM_EMAIL_MODE: "sandbox";
    PRODUCT_BASE_DOMAIN: "staging.musicsite.org";
    STRIPE_PAYMENTS_ENABLED: "true";
    ORGANIZATION_STORE: DurableObjectNamespace<import("./src/index").OrganizationStore>;
    FLEET_SCHEMA_WORKFLOW: Workflow<
      Parameters<import("./src/index").FleetSchemaWorkflow["run"]>[0]["payload"]
    >;
    PROVISIONING_WORKFLOW: Workflow<
      Parameters<import("./src/index").ProvisioningWorkflow["run"]>[0]["payload"]
    >;
    CUSTOM_DOMAIN_WORKFLOW: Workflow<
      Parameters<import("./src/index").CustomDomainWorkflow["run"]>[0]["payload"]
    >;
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
    APP_ENV: "production";
    BUILD_VERSION: "unreleased";
    CUSTOM_DOMAIN_PROVIDER_MODE: "disabled";
    EMAIL_EVENTS_DLQ_NAME: "choir-management-email-events-dlq-production";
    EMAIL_EVENTS_QUEUE_NAME: "choir-management-email-events-production";
    EXTERNAL_EFFECTS_MODE: "disabled";
    JOBS_DLQ_NAME: "choir-management-jobs-dlq-production";
    PLATFORM_EMAIL_FROM: "auth@invalid.example";
    PLATFORM_EMAIL_MODE: "disabled";
    PRODUCT_BASE_DOMAIN: "invalid.example";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "APP_ENV"
      | "BUILD_VERSION"
      | "CUSTOM_DOMAIN_PROVIDER_MODE"
      | "EMAIL_EVENTS_DLQ_NAME"
      | "EMAIL_EVENTS_QUEUE_NAME"
      | "EXTERNAL_EFFECTS_MODE"
      | "JOBS_DLQ_NAME"
      | "PLATFORM_EMAIL_ALLOWED_RECIPIENTS"
      | "PLATFORM_EMAIL_FROM"
      | "PLATFORM_EMAIL_MODE"
      | "PRODUCT_BASE_DOMAIN"
      | "STRIPE_PAYMENTS_ENABLED"
    >
  > {}
}
