import {
  communicationPlaceholderDefinitions,
  determineCommunicationPlaceholderContext,
  extractCommunicationPlaceholders,
  findCommunicationPlaceholderDefinition,
  hasEventDependentCommunicationPlaceholders,
  isPlaceholderCompatibleWithAudience,
  isPlaceholderCompatibleWithChannel,
  removeCommunicationPlaceholder,
  templateMatchesCommunicationContext,
  validateCommunicationContext,
  visibleCommunicationPlaceholders,
  type CommunicationAudienceLike,
  type CommunicationAudienceTarget,
  type CommunicationChannel,
  type CommunicationContextIssue,
  type CommunicationPlaceholderCategory,
  type CommunicationPlaceholderDefinition,
  type CommunicationPlaceholderContext,
  type CommunicationTemplateLike,
} from "@choir/domain";

export type CommunicationPlaceholder = CommunicationPlaceholderDefinition;
export {
  communicationPlaceholderDefinitions,
  determineCommunicationPlaceholderContext,
  determineCommunicationPlaceholderContext as communicationPlaceholderContext,
  extractCommunicationPlaceholders,
  findCommunicationPlaceholderDefinition,
  hasEventDependentCommunicationPlaceholders,
  isPlaceholderCompatibleWithAudience,
  isPlaceholderCompatibleWithChannel,
  removeCommunicationPlaceholder,
  templateMatchesCommunicationContext,
  validateCommunicationContext,
  visibleCommunicationPlaceholders,
  type CommunicationAudienceLike,
  type CommunicationAudienceTarget,
  type CommunicationChannel,
  type CommunicationContextIssue,
  type CommunicationPlaceholderCategory,
  type CommunicationPlaceholderDefinition,
  type CommunicationPlaceholderContext,
  type CommunicationTemplateLike,
};
