import type { CommandPaletteAction } from "./types";

export const staticNavigationItems: readonly CommandPaletteAction[] = [
  // Core Administration Pages
  {
    badge: "Page",
    category: "navigation",
    href: "/admin",
    id: "nav-admin-overview",
    subtitle: "Organization administrative overview & summary",
    title: "Admin Overview",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/roster",
    id: "nav-roster",
    subtitle: "Manage choir members, parts, and profile statuses",
    title: "Roster Management",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/events",
    id: "nav-events",
    subtitle: "Rehearsals, performances, RSVP tracking, and attendance",
    title: "Events & Calendar",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/library",
    id: "nav-music",
    subtitle: "Sheet music catalog, arrangements, and reference audio",
    title: "Music Library",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/reports?tab=music-folders",
    id: "nav-music-folders",
    subtitle: "Track physical folder return status across performances",
    title: "Music Folder Reports",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/seating",
    id: "nav-seating",
    subtitle: "Stage setups, riser layouts, and auto-paint seating charts",
    title: "Seating Charts",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/communications",
    id: "nav-communications",
    subtitle: "Broadcast emails, SMS announcements, and dispatch logs",
    title: "Communications",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/polls",
    id: "nav-polls",
    subtitle: "Volunteer signups, availability polls, and results",
    title: "Engagement Polls",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/communications?section=templates",
    id: "nav-comm-templates",
    subtitle: "Reusable email layouts and message placeholders",
    title: "Message Templates",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/settings/invitations",
    id: "nav-invitations",
    subtitle: "Invite singers, directors, and administrators to the portal",
    title: "Organization Invitations",
  },
  {
    badge: "Module",
    category: "navigation",
    href: "/admin/auditions",
    id: "nav-auditions",
    requiredModule: "auditions",
    subtitle: "Audition slots, applicant registration, and judging review",
    title: "Audition Management",
  },
  {
    badge: "Module",
    category: "navigation",
    href: "/admin/tickets",
    id: "nav-ticketing",
    requiredModule: "ticketing",
    subtitle: "Ticket tiers, orders, will-call door lists, and discounts",
    title: "Ticket Sales & Orders",
  },
  {
    badge: "Module",
    category: "navigation",
    href: "/admin/donations",
    id: "nav-donations",
    requiredModule: "donations",
    subtitle: "Donor contributions, offline gifts, and tax letters",
    title: "Donations & Patrons",
  },
  {
    badge: "Module",
    category: "navigation",
    href: "/admin/seasons",
    id: "nav-seasons",
    requiredModule: "dues",
    subtitle: "Active seasons, member dues rates, and collection status",
    title: "Seasons & Member Dues",
  },
  {
    badge: "Module",
    category: "navigation",
    href: "/admin/website",
    id: "nav-website",
    requiredModule: "website",
    subtitle: "Branded public website, about markdown, and media links",
    title: "Public Website",
  },
  {
    badge: "Page",
    category: "navigation",
    href: "/admin/settings",
    id: "nav-settings",
    subtitle: "Organization settings, integrations, branding, and audit log",
    title: "System Settings",
  },

  // Deep-Link Settings & Configuration Tabs
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/settings#general",
    id: "set-general",
    subtitle: "Organization name, logo, physical address, and subdomain",
    title: "General & Branding Settings",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/settings#calendar",
    id: "set-calendar",
    subtitle: "Timezone, default RSVP deadlines, and automated reminders",
    title: "Calendar & Timezone Settings",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/settings#communications",
    id: "set-communications",
    subtitle: "Brevo API key, custom sending domain, and reply-to address",
    title: "Communication Provider Settings",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/settings#payment",
    id: "set-payment",
    ownerOnly: true,
    subtitle: "Stripe Connect onboarding, direct charges, and negative liability",
    title: "Payment Account & Gateway (Owner)",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/roster?tab=config",
    id: "set-roster-automation",
    subtitle: "Parts taxonomy, Missed Performance automation, and On Break timeout",
    title: "Roster Automation & Parts Config",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/library/settings",
    id: "set-music-genres",
    subtitle: "Music genres registry and external publisher lookup URL template",
    title: "Music Library Settings & Genres",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/seating?tab=formations",
    id: "set-seating-formations",
    subtitle: "Column and row seating formation templates and color palettes",
    title: "Seating Formations & Templates",
  },
  {
    badge: "Settings",
    category: "settings",
    href: "/admin/settings#audit",
    id: "set-audit-history",
    subtitle: "Immutable chronological record of administrative operations",
    title: "Organization Audit History",
  },

  // Quick Action Commands
  {
    badge: "Action",
    category: "actions",
    href: "/admin/events?action=new",
    id: "act-create-event",
    subtitle: "Schedule a new rehearsal or performance event",
    title: "Create New Event",
  },
  {
    badge: "Action",
    category: "actions",
    href: "/admin/roster?action=add",
    id: "act-add-singer",
    subtitle: "Create a new roster profile or import via CSV",
    title: "Add Singer / Import Roster",
  },
  {
    badge: "Action",
    category: "actions",
    href: "/admin/communications?action=compose",
    id: "act-compose-message",
    subtitle: "Draft and broadcast an email/SMS communication",
    title: "Compose Communication",
  },
  {
    badge: "Action",
    category: "actions",
    href: "/admin/settings#export",
    id: "act-export-org",
    subtitle: "Generate portable ZIP export of all tenant records and files",
    title: "Export Organization Archive",
  },
  {
    badge: "Action",
    category: "actions",
    id: "act-toggle-theme",
    subtitle: "Switch between dark mode and light mode",
    title: "Toggle Theme (Light / Dark)",
  },
];
