import type { Hono } from "hono";
import type { WorkerHonoEnvironment } from "../helpers";

import { registerRoutes as registerAuthRoutes } from "../auth";
import { registerRoutes as registerCalendarRoutes } from "../calendar";
import { registerRoutes as registerOrganizationAccessRoutes } from "../organizationAccess";
import { registerRoutes as registerOrganizationAuditionLifecycleRoutes } from "../organizationAuditionLifecycle";
import { registerRoutes as registerOrganizationAuditionsRoutes } from "../organizationAuditions";
import { registerRoutes as registerOrganizationBrandingRoutes } from "../organizationBranding";
import { registerRoutes as registerOrganizationCalendarSettingsRoutes } from "../organizationCalendarSettings";
import { registerRoutes as registerOrganizationCommerceSettingsRoutes } from "../organizationCommerceSettings";
import { registerRoutes as registerOrganizationCommunicationsRoutes } from "../organizationCommunications";
import { registerRoutes as registerOrganizationDashboardRoutes } from "../organizationDashboard";
import { registerRoutes as registerOrganizationDomainsRoutes } from "../organizationDomains";
import { registerRoutes as registerOrganizationDonationRefundsRoutes } from "../organizationDonationRefunds";
import { registerRoutes as registerOrganizationDonationsRoutes } from "../organizationDonations";
import { registerRoutes as registerOrganizationEmailSettingsRoutes } from "../organizationEmailSettings";
import { registerRoutes as registerOrganizationEventAttendanceRoutes } from "../organizationEventAttendance";
import { registerRoutes as registerOrganizationEventCatalogRoutes } from "../organizationEventCatalog";
import { registerRoutes as registerOrganizationEventManagementRoutes } from "../organizationEventManagement";
import { registerRoutes as registerOrganizationEventSeatingRoutes } from "../organizationEventSeating";
import { registerRoutes as registerOrganizationEventsRoutes } from "../organizationEvents";
import { registerRoutes as registerOrganizationExportRoutes } from "../organizationExport";
import { registerRoutes as registerOrganizationFilesRoutes } from "../organizationFiles";
import { registerRoutes as registerOrganizationImpersonationRoutes } from "../organizationImpersonation";
import { registerRoutes as registerOrganizationInvitationsRoutes } from "../organizationInvitations";
import { registerRoutes as registerOrganizationModulesRoutes } from "../organizationModules";
import { registerRoutes as registerOrganizationMusicCatalogRoutes } from "../organizationMusicCatalog";
import { registerRoutes as registerOrganizationMusicFolderReportRoutes } from "../organizationMusicFolderReports";
import { registerRoutes as registerOrganizationMusicMutationsRoutes } from "../organizationMusicMutations";
import { registerRoutes as registerOrganizationPatronsRoutes } from "../organizationPatrons";
import { registerRoutes as registerOrganizationPaymentSettingsRoutes } from "../organizationPaymentSettings";
import { registerRoutes as registerOrganizationPollsRoutes } from "../organizationPolls";
import { registerRoutes as registerOrganizationProfileDeliveriesRoutes } from "../organizationProfileDeliveries";
import { registerRoutes as registerOrganizationProfileMutationsRoutes } from "../organizationProfileMutations";
import { registerRoutes as registerOrganizationProfilePhotosRoutes } from "../organizationProfilePhotos";
import { registerRoutes as registerOrganizationProfileRecordsRoutes } from "../organizationProfileRecords";
import { registerRoutes as registerOrganizationProfilesRoutes } from "../organizationProfiles";
import { registerRoutes as registerOrganizationResourcesRoutes } from "../organizationResources";
import { registerRoutes as registerOrganizationRosterSettingsRoutes } from "../organizationRosterSettings";
import { registerRoutes as registerOrganizationRsvpExportsRoutes } from "../organizationRsvpExports";
import { registerRoutes as registerOrganizationSearchRoutes } from "../organizationSearch";
import { registerRoutes as registerOrganizationSeasonsRoutes } from "../organizationSeasons";
import { registerRoutes as registerOrganizationSeatingRoutes } from "../organizationSeating";
import { registerRoutes as registerOrganizationTicketingRoutes } from "../organizationTicketing";
import { registerRoutes as registerOrganizationTicketingOrdersRoutes } from "../organizationTicketingOrders";
import { registerRoutes as registerOrganizationTokensRoutes } from "../organizationTokens";
import { registerRoutes as registerOrganizationWebsiteRoutes } from "../organizationWebsite";

export function registerOrganizationGroupRoutes(router: Hono<WorkerHonoEnvironment>): void {
  registerAuthRoutes(router);
  registerCalendarRoutes(router);
  registerOrganizationAccessRoutes(router);
  registerOrganizationAuditionLifecycleRoutes(router);
  registerOrganizationAuditionsRoutes(router);
  registerOrganizationBrandingRoutes(router);
  registerOrganizationCalendarSettingsRoutes(router);
  registerOrganizationCommerceSettingsRoutes(router);
  registerOrganizationCommunicationsRoutes(router);
  registerOrganizationDashboardRoutes(router);
  registerOrganizationDomainsRoutes(router);
  registerOrganizationDonationRefundsRoutes(router);
  registerOrganizationDonationsRoutes(router);
  registerOrganizationEmailSettingsRoutes(router);
  registerOrganizationEventAttendanceRoutes(router);
  registerOrganizationEventCatalogRoutes(router);
  registerOrganizationEventManagementRoutes(router);
  registerOrganizationEventsRoutes(router);
  registerOrganizationEventSeatingRoutes(router);
  registerOrganizationExportRoutes(router);
  registerOrganizationFilesRoutes(router);
  registerOrganizationImpersonationRoutes(router);
  registerOrganizationInvitationsRoutes(router);
  registerOrganizationModulesRoutes(router);
  registerOrganizationMusicCatalogRoutes(router);
  registerOrganizationMusicFolderReportRoutes(router);
  registerOrganizationMusicMutationsRoutes(router);
  registerOrganizationPatronsRoutes(router);
  registerOrganizationPaymentSettingsRoutes(router);
  registerOrganizationPollsRoutes(router);
  registerOrganizationProfileDeliveriesRoutes(router);
  registerOrganizationProfileMutationsRoutes(router);
  registerOrganizationProfilePhotosRoutes(router);
  registerOrganizationProfileRecordsRoutes(router);
  registerOrganizationProfilesRoutes(router);
  registerOrganizationResourcesRoutes(router);
  registerOrganizationRosterSettingsRoutes(router);
  registerOrganizationRsvpExportsRoutes(router);
  registerOrganizationSearchRoutes(router);
  registerOrganizationSeasonsRoutes(router);
  registerOrganizationSeatingRoutes(router);
  registerOrganizationTicketingRoutes(router);
  registerOrganizationTicketingOrdersRoutes(router);
  registerOrganizationTokensRoutes(router);
  registerOrganizationWebsiteRoutes(router);
}
